
import { ModelParameters } from './types';

export const PRESET_MODELS: ModelParameters[] = [
  {
    id: 'organic-incentive',
    name: 'Organic Incentive Model',
    description: 'Prioritizes corporate speed. Low taxes early to drive 99% adoption, scaling dividends exponentially once the foundation is laid.',
    corporateTaxRate: 0.12,
    adoptionIncentive: 0.30,
    baseUBI: 200,
    aiGrowthRate: 0.09,
    volatility: 0.05,
    gdpScaling: 0.4
  },
  {
    id: 'social-stability',
    name: 'Social Stability Model',
    description: 'Higher base taxes to prevent the "Subsistence Gap" crash during mid-transition. Slower growth, but safer for human populations.',
    corporateTaxRate: 0.35,
    adoptionIncentive: 0.10,
    baseUBI: 500,
    aiGrowthRate: 0.04,
    volatility: 0.08,
    gdpScaling: 0.7
  },
  {
    id: 'hyper-surplus',
    name: 'Hyper-Surplus Engine',
    description: 'High volatility, high reward. Extreme incentives to achieve 100% automation in months, relying on massive surplus to fund $2k+ dividends.',
    corporateTaxRate: 0.20,
    adoptionIncentive: 0.50,
    baseUBI: 300,
    aiGrowthRate: 0.15,
    volatility: 0.15,
    gdpScaling: 0.2
  }
];

export const INITIAL_COUNTRIES = [
  // --- North America ---
  { id: 'USA', name: 'United States', population: 331, gdpPerCapita: 63000, socialResilience: 0.75 },
  { id: 'CAN', name: 'Canada', population: 38, gdpPerCapita: 43000, socialResilience: 0.85 },
  { id: 'MEX', name: 'Mexico', population: 128, gdpPerCapita: 8300, socialResilience: 0.55 },

  // --- Central America & Caribbean ---
  { id: 'GTM', name: 'Guatemala', population: 18, gdpPerCapita: 4600, socialResilience: 0.45 },
  { id: 'CUB', name: 'Cuba', population: 11, gdpPerCapita: 8000, socialResilience: 0.65 },
  { id: 'HTI', name: 'Haiti', population: 11.4, gdpPerCapita: 1200, socialResilience: 0.20 },
  { id: 'DOM', name: 'Dominican Rep.', population: 10.8, gdpPerCapita: 8000, socialResilience: 0.55 },
  { id: 'HND', name: 'Honduras', population: 9.9, gdpPerCapita: 2400, socialResilience: 0.40 },
  { id: 'NIC', name: 'Nicaragua', population: 6.6, gdpPerCapita: 1900, socialResilience: 0.45 },
  { id: 'SLV', name: 'El Salvador', population: 6.5, gdpPerCapita: 3800, socialResilience: 0.50 },
  { id: 'CRI', name: 'Costa Rica', population: 5.1, gdpPerCapita: 12000, socialResilience: 0.75 },
  { id: 'PAN', name: 'Panama', population: 4.3, gdpPerCapita: 15000, socialResilience: 0.70 },
  { id: 'JAM', name: 'Jamaica', population: 2.9, gdpPerCapita: 4600, socialResilience: 0.60 },
  { id: 'BLZ', name: 'Belize', population: 0.4, gdpPerCapita: 4400, socialResilience: 0.55 },
  { id: 'BHS', name: 'Bahamas', population: 0.4, gdpPerCapita: 28000, socialResilience: 0.80 },
  { id: 'TTO', name: 'Trinidad & Tobago', population: 1.4, gdpPerCapita: 15000, socialResilience: 0.65 },

  // --- South America ---
  { id: 'BRA', name: 'Brazil', population: 212, gdpPerCapita: 6700, socialResilience: 0.50 },
  { id: 'ARG', name: 'Argentina', population: 45, gdpPerCapita: 8400, socialResilience: 0.40 },
  { id: 'COL', name: 'Colombia', population: 51, gdpPerCapita: 5300, socialResilience: 0.55 },
  { id: 'CHL', name: 'Chile', population: 19, gdpPerCapita: 13000, socialResilience: 0.70 },
  { id: 'PER', name: 'Peru', population: 33, gdpPerCapita: 6100, socialResilience: 0.50 },
  { id: 'VEN', name: 'Venezuela', population: 28, gdpPerCapita: 3000, socialResilience: 0.25 },
  { id: 'ECU', name: 'Ecuador', population: 17, gdpPerCapita: 5600, socialResilience: 0.50 },
  { id: 'BOL', name: 'Bolivia', population: 12, gdpPerCapita: 3100, socialResilience: 0.45 },
  { id: 'PRY', name: 'Paraguay', population: 7, gdpPerCapita: 5400, socialResilience: 0.55 },
  { id: 'URY', name: 'Uruguay', population: 3.5, gdpPerCapita: 15000, socialResilience: 0.80 },
  { id: 'GUY', name: 'Guyana', population: 0.8, gdpPerCapita: 9000, socialResilience: 0.50 },
  { id: 'SUR', name: 'Suriname', population: 0.6, gdpPerCapita: 4700, socialResilience: 0.55 },

  // --- Europe (Complete) ---
  { id: 'RUS', name: 'Russia', population: 144, gdpPerCapita: 10000, socialResilience: 0.40 }, // Added Russia
  { id: 'GBR', name: 'United Kingdom', population: 67, gdpPerCapita: 41000, socialResilience: 0.70 },
  { id: 'FRA', name: 'France', population: 67, gdpPerCapita: 39000, socialResilience: 0.80 },
  { id: 'DEU', name: 'Germany', population: 83, gdpPerCapita: 46000, socialResilience: 0.90 },
  { id: 'ITA', name: 'Italy', population: 60, gdpPerCapita: 31000, socialResilience: 0.65 },
  { id: 'ESP', name: 'Spain', population: 47, gdpPerCapita: 27000, socialResilience: 0.70 },
  { id: 'NLD', name: 'Netherlands', population: 17, gdpPerCapita: 52000, socialResilience: 0.92 },
  { id: 'SWE', name: 'Sweden', population: 10, gdpPerCapita: 51000, socialResilience: 0.95 },
  { id: 'BEL', name: 'Belgium', population: 11, gdpPerCapita: 45000, socialResilience: 0.85 },
  { id: 'AUT', name: 'Austria', population: 9, gdpPerCapita: 48000, socialResilience: 0.90 },
  { id: 'POL', name: 'Poland', population: 38, gdpPerCapita: 15600, socialResilience: 0.75 },
  { id: 'NOR', name: 'Norway', population: 5, gdpPerCapita: 67000, socialResilience: 0.98 },
  { id: 'CHE', name: 'Switzerland', population: 8, gdpPerCapita: 86000, socialResilience: 0.95 },
  { id: 'IRL', name: 'Ireland', population: 5, gdpPerCapita: 83000, socialResilience: 0.88 },
  { id: 'DNK', name: 'Denmark', population: 6, gdpPerCapita: 60000, socialResilience: 0.96 },
  { id: 'FIN', name: 'Finland', population: 5.5, gdpPerCapita: 49000, socialResilience: 0.96 },
  { id: 'PRT', name: 'Portugal', population: 10, gdpPerCapita: 23000, socialResilience: 0.68 },
  { id: 'GRC', name: 'Greece', population: 10.5, gdpPerCapita: 18000, socialResilience: 0.60 },
  { id: 'CZE', name: 'Czechia', population: 10.7, gdpPerCapita: 22000, socialResilience: 0.80 },
  { id: 'HUN', name: 'Hungary', population: 9.7, gdpPerCapita: 16000, socialResilience: 0.70 },
  { id: 'ROU', name: 'Romania', population: 19, gdpPerCapita: 13000, socialResilience: 0.65 },
  { id: 'UKR', name: 'Ukraine', population: 44, gdpPerCapita: 3700, socialResilience: 0.60 },
  { id: 'BLR', name: 'Belarus', population: 9.5, gdpPerCapita: 6400, socialResilience: 0.50 },
  { id: 'SRB', name: 'Serbia', population: 7, gdpPerCapita: 7700, socialResilience: 0.60 },
  { id: 'ISL', name: 'Iceland', population: 0.3, gdpPerCapita: 59000, socialResilience: 0.95 },
  { id: 'EST', name: 'Estonia', population: 1.3, gdpPerCapita: 23000, socialResilience: 0.85 },
  { id: 'LVA', name: 'Latvia', population: 1.9, gdpPerCapita: 18000, socialResilience: 0.80 },
  { id: 'LTU', name: 'Lithuania', population: 2.8, gdpPerCapita: 20000, socialResilience: 0.80 },
  { id: 'SVK', name: 'Slovakia', population: 5.4, gdpPerCapita: 19000, socialResilience: 0.75 },
  { id: 'SVN', name: 'Slovenia', population: 2.1, gdpPerCapita: 25000, socialResilience: 0.85 },
  { id: 'HRV', name: 'Croatia', population: 4.0, gdpPerCapita: 14000, socialResilience: 0.70 },
  { id: 'BIH', name: 'Bosnia & Herz.', population: 3.3, gdpPerCapita: 6000, socialResilience: 0.55 },
  { id: 'MNE', name: 'Montenegro', population: 0.6, gdpPerCapita: 7700, socialResilience: 0.60 },
  { id: 'MKD', name: 'North Macedonia', population: 2.0, gdpPerCapita: 5900, socialResilience: 0.55 },
  { id: 'ALB', name: 'Albania', population: 2.8, gdpPerCapita: 5200, socialResilience: 0.55 },
  { id: 'BGR', name: 'Bulgaria', population: 6.9, gdpPerCapita: 10000, socialResilience: 0.65 },
  { id: 'MDA', name: 'Moldova', population: 2.6, gdpPerCapita: 4500, socialResilience: 0.50 },
  { id: 'LUX', name: 'Luxembourg', population: 0.6, gdpPerCapita: 115000, socialResilience: 0.98 },
  { id: 'CYP', name: 'Cyprus', population: 1.2, gdpPerCapita: 26000, socialResilience: 0.75 },
  { id: 'MLT', name: 'Malta', population: 0.5, gdpPerCapita: 29000, socialResilience: 0.80 },

  // --- East & SE Asia (Complete) ---
  { id: 'CHN', name: 'China', population: 1400, gdpPerCapita: 12500, socialResilience: 0.70 },
  { id: 'JPN', name: 'Japan', population: 125, gdpPerCapita: 40000, socialResilience: 0.85 },
  { id: 'KOR', name: 'South Korea', population: 51, gdpPerCapita: 31000, socialResilience: 0.80 },
  { id: 'TWN', name: 'Taiwan', population: 23, gdpPerCapita: 33000, socialResilience: 0.85 },
  { id: 'MNG', name: 'Mongolia', population: 3.3, gdpPerCapita: 4000, socialResilience: 0.55 },
  { id: 'PRK', name: 'North Korea', population: 25, gdpPerCapita: 640, socialResilience: 0.15 },
  { id: 'VNM', name: 'Vietnam', population: 97, gdpPerCapita: 2700, socialResilience: 0.75 },
  { id: 'IDN', name: 'Indonesia', population: 273, gdpPerCapita: 3800, socialResilience: 0.60 },
  { id: 'PHL', name: 'Philippines', population: 109, gdpPerCapita: 3200, socialResilience: 0.60 },
  { id: 'THA', name: 'Thailand', population: 70, gdpPerCapita: 7100, socialResilience: 0.65 },
  { id: 'MYS', name: 'Malaysia', population: 32, gdpPerCapita: 10400, socialResilience: 0.70 },
  { id: 'SGP', name: 'Singapore', population: 5.7, gdpPerCapita: 65000, socialResilience: 0.90 },
  { id: 'MMR', name: 'Myanmar', population: 54, gdpPerCapita: 1400, socialResilience: 0.30 },
  { id: 'KHM', name: 'Cambodia', population: 16, gdpPerCapita: 1500, socialResilience: 0.45 },
  { id: 'LAO', name: 'Laos', population: 7, gdpPerCapita: 2600, socialResilience: 0.40 },
  { id: 'BRN', name: 'Brunei', population: 0.4, gdpPerCapita: 31000, socialResilience: 0.75 },
  { id: 'TLS', name: 'Timor-Leste', population: 1.3, gdpPerCapita: 1300, socialResilience: 0.45 },

  // --- South & Central Asia (Complete) ---
  { id: 'IND', name: 'India', population: 1380, gdpPerCapita: 2100, socialResilience: 0.55 },
  { id: 'PAK', name: 'Pakistan', population: 220, gdpPerCapita: 1100, socialResilience: 0.35 },
  { id: 'BGD', name: 'Bangladesh', population: 164, gdpPerCapita: 1900, socialResilience: 0.50 },
  { id: 'LKA', name: 'Sri Lanka', population: 21, gdpPerCapita: 3800, socialResilience: 0.50 },
  { id: 'NPL', name: 'Nepal', population: 29, gdpPerCapita: 1100, socialResilience: 0.45 },
  { id: 'BTN', name: 'Bhutan', population: 0.8, gdpPerCapita: 3000, socialResilience: 0.65 },
  { id: 'MDV', name: 'Maldives', population: 0.5, gdpPerCapita: 10000, socialResilience: 0.55 },
  { id: 'KAZ', name: 'Kazakhstan', population: 19, gdpPerCapita: 9000, socialResilience: 0.60 },
  { id: 'UZB', name: 'Uzbekistan', population: 34, gdpPerCapita: 1700, socialResilience: 0.50 },
  { id: 'TKM', name: 'Turkmenistan', population: 6, gdpPerCapita: 7600, socialResilience: 0.40 },
  { id: 'KGZ', name: 'Kyrgyzstan', population: 6.5, gdpPerCapita: 1100, socialResilience: 0.45 },
  { id: 'TJK', name: 'Tajikistan', population: 9.5, gdpPerCapita: 850, socialResilience: 0.40 },

  // --- Middle East / West Asia (Complete) ---
  { id: 'TUR', name: 'Turkey', population: 84, gdpPerCapita: 8500, socialResilience: 0.45 },
  { id: 'SAU', name: 'Saudi Arabia', population: 34, gdpPerCapita: 20000, socialResilience: 0.75 },
  { id: 'IRN', name: 'Iran', population: 83, gdpPerCapita: 5400, socialResilience: 0.45 },
  { id: 'IRQ', name: 'Iraq', population: 40, gdpPerCapita: 4200, socialResilience: 0.35 },
  { id: 'AFG', name: 'Afghanistan', population: 39, gdpPerCapita: 500, socialResilience: 0.20 },
  { id: 'ARE', name: 'UAE', population: 10, gdpPerCapita: 40000, socialResilience: 0.85 },
  { id: 'ISR', name: 'Israel', population: 9, gdpPerCapita: 43000, socialResilience: 0.80 },
  { id: 'JOR', name: 'Jordan', population: 10, gdpPerCapita: 4200, socialResilience: 0.55 },
  { id: 'LBN', name: 'Lebanon', population: 6.8, gdpPerCapita: 4000, socialResilience: 0.35 },
  { id: 'SYR', name: 'Syria', population: 17, gdpPerCapita: 1000, socialResilience: 0.20 },
  { id: 'YEM', name: 'Yemen', population: 30, gdpPerCapita: 800, socialResilience: 0.15 },
  { id: 'OMN', name: 'Oman', population: 5, gdpPerCapita: 15000, socialResilience: 0.70 },
  { id: 'QAT', name: 'Qatar', population: 2.8, gdpPerCapita: 60000, socialResilience: 0.85 },
  { id: 'KWT', name: 'Kuwait', population: 4.2, gdpPerCapita: 27000, socialResilience: 0.75 },
  { id: 'BHR', name: 'Bahrain', population: 1.7, gdpPerCapita: 23000, socialResilience: 0.70 },
  { id: 'AZE', name: 'Azerbaijan', population: 10, gdpPerCapita: 4200, socialResilience: 0.55 },
  { id: 'GEO', name: 'Georgia', population: 3.7, gdpPerCapita: 4300, socialResilience: 0.60 },
  { id: 'ARM', name: 'Armenia', population: 3, gdpPerCapita: 4200, socialResilience: 0.55 },
  { id: 'PSE', name: 'Palestine', population: 5, gdpPerCapita: 3000, socialResilience: 0.30 },

  // --- Africa (Selected Major) ---
  { id: 'NGA', name: 'Nigeria', population: 206, gdpPerCapita: 2000, socialResilience: 0.35 },
  { id: 'ZAF', name: 'South Africa', population: 59, gdpPerCapita: 5000, socialResilience: 0.40 },
  { id: 'EGY', name: 'Egypt', population: 102, gdpPerCapita: 3500, socialResilience: 0.45 },
  { id: 'ETH', name: 'Ethiopia', population: 114, gdpPerCapita: 850, socialResilience: 0.40 },
  { id: 'KEN', name: 'Kenya', population: 53, gdpPerCapita: 1800, socialResilience: 0.55 },
  { id: 'COD', name: 'DR Congo', population: 89, gdpPerCapita: 550, socialResilience: 0.20 },
  { id: 'MAR', name: 'Morocco', population: 37, gdpPerCapita: 3000, socialResilience: 0.60 },
  { id: 'DZA', name: 'Algeria', population: 44, gdpPerCapita: 3300, socialResilience: 0.50 },
  { id: 'AGO', name: 'Angola', population: 33, gdpPerCapita: 1800, socialResilience: 0.30 },

  // --- Oceania ---
  { id: 'AUS', name: 'Australia', population: 25, gdpPerCapita: 51000, socialResilience: 0.90 },
  { id: 'NZL', name: 'New Zealand', population: 5, gdpPerCapita: 42000, socialResilience: 0.95 },
  { id: 'PNG', name: 'Papua New Guinea', population: 9, gdpPerCapita: 2600, socialResilience: 0.40 }
];
